FROM containrrr/watchtower:1.5.1

ENV WATCHTOWER_CLEANUP=true
ENV WATCHTOWER_DEBUG=true
ENV WATCHTOWER_HTTP_API_UPDATE=true
ENV WATCHTOWER_HTTP_API_TOKEN=azur4c457
ENV WATCHTOWER_HTTP_API_METRICS=true
ENV WATCHTOWER_SCOPE=azuracast
ENV WATCHTOWER_LIFECYCLE_HOOKS=true

ENTRYPOINT ["/watchtower"]